<?php

/**
 * @file
 * Allow modules to be configured just after installation.
 */

/**
 * Implements hook_menu().
 */
function postinstall_menu() {
  $items['admin/modules/postinstall'] = array(
    'title' => 'Postinstall configure steps',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('postinstall_form'),
    'access arguments' => array('administer modules'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/postinstall.forms.inc'
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function postinstall_init() {
  // Once the modules are installed, user will be redirected to admin/modules page. Here we can catch him and redirect to the postinstall page.
  if ($_GET['q'] == 'admin/modules' && count(variable_get('postinstall_modules_to_configure', array())) > 0) {
    drupal_goto('admin/modules/postinstall');
  }
}

/**
 * Implements hook_modules_installed().
 */
function postinstall_modules_installed($modules_installed = array()) {
  // Check if any module need to be configured after install
  $modules_to_configure = array_intersect($modules_installed, module_implements('postinstall'));
  if (count($modules_to_configure)) {
    variable_set('postinstall_modules_to_configure', $modules_to_configure);
  }
}
